Implement submitting the solutions and recording them, ALSO
ALSO!

Remove solver_args from everywhere in Rust code, because trying to parse them out would crash everything.

For example:

// eprintln!("here");
// TODO: there's a bug here
// thread 'main' panicked at 'error retrieving column solver_args: error deserializing column 6: invalid type: map, expected a sequence at line 1 column 0', /home/sweater/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.7.7/src/row.rs:151:25
// let solver_args: Json<Option<Vec<String>>> = r.get("solver_args");
// eprintln!("there");